### ISSUE TITLE
Android 11 Unable to instantiate codec

### ISSUE THREAD

**Issue by madlyyouitv** [google/ExoPlayer#9962]
I'm seeing the same issue for Android 11 reported in https://github.com/google/ExoPlayer/issues/8696  but this time for Audio decoder

```
                 ACodec  E  Unable to instantiate codec 'OMX.Berlin.audio_decoder.ac3' with err 0xfffffff4.
                         E  signalError(omxError 0xfffffff4, internalError -12)
             MediaCodec  E  Codec reported err 0xfffffff4, actionCode 0, while in state 1
         MediaCodec-JNI  W  try to release MediaCodec from JMediaCodec::~JMediaCodec()...
                         W  done releasing MediaCodec from JMediaCodec::~JMediaCodec().
     MediaCodecRenderer  W  Failed to initialize decoder: OMX.Berlin.audio_decoder.ac3
                         W    android.media.MediaCodec$CodecException: Failed to initialize OMX.Berlin.audio_decoder.ac3, error 0xfffffff4

```

I know that a fix for it was added to version `2.16.1` but what if we're using an older version, is it possible to have a similar workaround for Audio codec release similar to the one mentioned in https://github.com/google/ExoPlayer/issues/8696 for `MediaCodecVideoRenderer`?

**Comment by ojw28** [comment]
I don't think this is the same as #8696 (or the audio equivalent of it). #8696 is related to switching between secure and non-secure video decoders. There's no such thing as a secure audio decoder as of today, and so switching between secure and non-secure audio decoders isn't something that ever happens.

It feels more likely to me that `OMX.Berlin.audio_decoder.ac3` is just a buggy decoder implementation. If you'd like us to investigate this as a bug, please file a [bug report here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=), including all of the requested information. Thanks!
