### ISSUE TITLE
How to know the callback of each video playback completion

### ISSUE THREAD

**Issue by LiuDongCai** [google/ExoPlayer#9963]
player.setRepeatMode(Player.REPEAT_MODE_ALL)

How to know the callback of each video playback completion？

**Comment by ojw28** [comment]
I think `Player.Listener.onMediaItemTransition` is what you want. Note that the `reason` parameter will tell you why the transition is occurring. You're probably interested in `reason=MEDIA_ITEM_TRANSITION_REASON_AUTO`, which is the reason used when playback naturally advances to the next video. You may be interested in traisions with `reason=MEDIA_ITEM_TRANSITION_REASON_REPEAT` as well.
