### ISSUE TITLE
cache for dash

### ISSUE THREAD

**Issue by siavashabdoli** [google/ExoPlayer#997]
I really need to write effective cache for dash type(or keep it on memory if it's not so large). I want user can seek forward on buffered data without losing data and seek a little backward (for example keep last 2 minutes) that's important because users have bad feeling when they stream some data twice. they pay money for traffic and I know this is not to much but here is user feeling!!! also I write a program for Iranian users and traffic is expensive approximately in Iran. how to do it? which file have to edit? can I use the cache classes in upstream package?how?
I try this for audio and video but it does not work.
Cache cache = new SimpleCache(context.getCacheDir(), new LeastRecentlyUsedCacheEvictor(1024 * 1024 * 10));
      // Build the video renderer.
      DataSource videoDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
      CacheDataSource videoCacheDataSource= new CacheDataSource(cache, videoDataSource, false, false);
      ChunkSource videoChunkSource =new DashChunkSource(videoCacheDataSource,new AdaptiveEvaluator(bandwidthMeter)
              ,LIVE_EDGE_LATENCY_MS,AdaptationSet.TYPE_VIDEO);

**Comment by ojw28** [comment]
Closing because this is neither a bug or feature request (the feature request is already tracked by https://github.com/google/ExoPlayer/issues/420).
