### ISSUE TITLE
Unreachable code found in FLAC parser

### ISSUE THREAD

**Issue by ktmf01** [google/ExoPlayer#9970]
I've been looking at a [oss-fuzz fuzzer based on some Exoplayer code](https://github.com/google/oss-fuzz/pull/4073), but I can't seem to figure out what it does, where it is used and how it works.

Anyway, I found quite a bit of unreachable code. I hoped perhaps comments on this could help me understand it.

https://github.com/google/ExoPlayer/blob/86afae9c3e01506fd51adb892010a771a055d579/extensions/flac/src/main/jni/flac_parser.cc#L365-L417

Code from line 380 is unreachable.

- line 366 `mWriteCompleted = false;`
-  that means line 373 `if (!mWriteCompleted) { ` is always true
- so code past line 379 `return -1;` is never used

**Comment by ojw28** [comment]
> that means line 373 `if (!mWriteCompleted) {` is always true

Does it? Note that `mWriteCompleted` is not a local variable. I would assume L368 can cause `FLACParser::writeCallback` to be called, which will set `mWriteCompleted = true`.

**Comment by ktmf01** [comment]
> Note that `mWriteCompleted` is not a local variable.

Ah, I completely missed that part. You are right, this is probably not an issue at all then.
