### ISSUE TITLE
Sound plays but no video unless you drag the scrub bar

### ISSUE THREAD

**Issue by jonfabris** [google/ExoPlayer#9974]
Sound plays normally.
Video does not show but if you drag the scrubber to any part of the video it will draw the one frame you dragged to but video will freeze there (sound continues to play normally)
I tried streaming several different videos, same thing.
This happens on two different emulators I tried.

`        player = ExoPlayer.Builder(this).build()
        // Bind the player to the view.
        playerView.setPlayer(player)
        val mediaItem = MediaItem.fromUri(
            videoUri!!
        )
        player!!.setMediaItem(mediaItem)
        player!!.prepare()
        player!!.play()
`

exoplayer:2.16.1

`                <com.google.android.exoplayer2.ui.PlayerView
                    android:id="@+id/playerView"
                    android:layout_width="match_parent"
                    android:layout_height="200dp"
                    android:layout_marginTop="8dp"
                    app:layout_constraintDimensionRatio="16:9"
                    app:show_buffering="always"
                    />`

**Comment by jonfabris** [comment]
Tried on motorola moto G6 play device and it works fine.

**Comment by icbaker** [comment]
> This happens on two different emulators I tried.

Please provide precise information about what emulator images you were using.

Does this issue reproduce in the [demo app](https://exoplayer.dev/demo-application.html)? If so, please provide media we can use to reproduce the issue.
