### ISSUE TITLE
Cache content is sometimes wrong

### ISSUE THREAD

**Issue by nchungdev** [google/ExoPlayer#9976]
I've been using ExoPlayer to play and pre-caching audio, I got an issue (rarely): play song A, the first part is from another song, the second part is from song A (sometimes, all content is from another song). I only got this error a few times and can't reproduce it.
My flow pre-caching: 
- Play a song playlist, while the song was playing (about to mid position) I started another thread to preload the next songs (about 4 songs). In that thread, I called `CacheUtil.cache` to cache a part of the song, this is sequential (all preloading songs are the same thread).
- I've initialized ExoPlayer in the remote process, pre-caching song and play song are in remote process (same instance cache)

I've searched websites and forums like stackoverflow.com for issues similar to this but I couldn't find anything useful.

- ExoPlayer version number: 2.9.5

**Comment by icbaker** [comment]
There isn't enough information here to reproduce and understand your problem. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by nchungdev** [comment]
I'm so sorry, this issue was reported from the user, it just occurs randomly, I can't give more information, so will close this issue. Tks for the support.
