### ISSUE TITLE
Change metadata for a MediaItem during playback

### ISSUE THREAD

**Issue by NikSatyr** [google/ExoPlayer#9978]
I'm having a hard time figuring out how to supply custom metadata for the ExoPlayer (or maybe it's better to say side-load). We support some sort of radio functionality, which is delivered via `ProgressiveMediaSource`. The problem is that the radio stream may contain malformed metadata due to the human factor (e.g. incorrect title, missing artwork). However, we have a dedicated "now playing" endpoint on our server that returns 100% accurate metadata (don't ask me why :)). 

What I need to achieve is to periodically update the metadata (by calling the above mentioned endpoint) (for instance to update the track info in the notification) without re-setting the media item with the radio url. This is because the radio stream url is always the same and we set it only once, while songs on the radio are obviously being changed, and we'd like to reflect the song changes (title, artist, artwork etc) in the notification.

Previously we've been using `mediaSession.setMetadata()` for this purpose, but as we migrated to media2 this method is marked as library restricted, so I don't think it's a good option.

Could you please advise the solution?

**Comment by icbaker** [comment]
I believe [`Player#setPlaylistMetadata(MediaMetadata)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#setPlaylistMetadata(com.google.android.exoplayer2.MediaMetadata)) should work for this use-case. Can you give that a try?

If that doesn't work, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by NikSatyr** [comment]
yep, I've already tried `Player.setPlaylistMetadata()` and it did not work. As far as I can see in the ExoPlayer source code, it does not actually affect anything important.

you can find a reproducible example here: https://github.com/NikSatyr/media2-radio. please see `RadioMetadataUpdater` class as it's responsible for fetching the radio metadata. I've grabbed the BBC radio stream URL as it does not provide correct metadata for the player notification manager, so it pretty much resembles our production situation. Let's assume that metadata returned by `getCustomMetadata()` is fully correct (in the real app we'd make an API call there) and should be displayed in the notification. So far I have not managed to achieve it.

PS: Make sure you follow the instructions from the README to setup the ExoPlayer locally (I understand that ExoPlayer devs perfectly know how to do this, but still don't forget to do so :))

**Comment by NikSatyr** [comment]
I'd also like to point out that we need this metadata not only for the notification (so some tweaks to MediaDescriptionAdapter would not be enough), but for `AnalyticsListener` & some other parts. Thus we need to feed this correct metadata directly into the player / `MediaSession`

**Comment by NikSatyr** [comment]
@icbaker sorry to bother you, but this blocks our development process. did you have a chance to take a look?

**Comment by NikSatyr** [comment]
any updates here?

**Comment by icbaker** [comment]
Sorry for the delay looking into this. Thanks for the repro project, it was really helpful and nice and simple.

This is a limitation of ExoPlayer: It's not currently possible to change the **item** metadata of a currently-playing `MediaItem` - because if you try and change the whole `MediaItem` it will result in the whole `MediaSource` being re-created, and playback will not be continuous. It's the same issue tracked by https://github.com/androidx/media/issues/33.

I'm going to mark this as an enhancement.

**Comment by npasyuk** [comment]
Hi, when is an update planned with these changes?

**Comment by icbaker** [comment]
This is now possible using [`Player.replaceMediaItem(s)`](https://developer.android.com/reference/kotlin/androidx/media3/common/Player#replaceMediaItem(int,androidx.media3.common.MediaItem)).
