### ISSUE TITLE
SeekTo() works incorrectly on stream

### ISSUE THREAD

**Issue by don11995** [google/ExoPlayer#998]
Hi! I decided to test the player on the different types of video to check out why my server does not return the length of a video file. Correspondingly, the first question:
I'm using the following video:
```
http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov
```
In this video everything works as expected, player returns the duration of the video, but the positioning is not working - video starts play from begining, although the play/pause works well. What am I doing wrong?
And the second question: can You show me the part of the code, where the player determining the duration of the video from the server? Why is my server always returns zero duration? Thank you in advance.
Also, I tested my server videos in VLC player and in FFMpeg and I got next results:
1. ExoPlayer's duration is 0 and seekTo not working.
On "Big buck bunny" video, only seekTo not working, duration not 0.
2. VLC's duration is 0, but seekTo works fine by percent parameter.
On "Big buck bunny video", pause works as stop - video starts from the begining, duration not 0.
3. FFMpeg's duration not 0 and seekTo also works normally.
On "Big buck bunny" video all working fine.

FFMpeg was tested on iOS, but as I know - VLC is a wrapper of FFMpeg on Android (not sure).
ExoPlayer works mostly stable than the others players.

I'm using ExoPlayer for online streaming video that placed on server or channels in real time only.

**Comment by ojw28** [comment]
I tried taking the current version of the demo app from both `master` and `dev`, and adding the sample you linked to as:
```
new Sample("TEST",
    "http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov",
    PlayerActivity.TYPE_OTHER),
```
The duration is reported correctly *and* seeking works correctly too.

If your live streams are just MPEG-TS then there is no support for passing the duration or seeking within the stream.
