### ISSUE TITLE
My FLV Live network delay causes me to play the screen is not up to date, how should I solve it ？

### ISSUE THREAD

**Issue by tmi111** [google/ExoPlayer#9981]
My FLV Live network delay causes me to play the screen is not up to date, how should I solve it ？

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
