### ISSUE TITLE
Is this the right way to change to software decoder in Exoplayer 

### ISSUE THREAD

**Issue by sagarNapps10x** [google/ExoPlayer#9983]
>Hey I'm not sure if this will help you. From what I understand with Exoplayer it will attempt to choose the best codec for you, it checks to see what hardware acceleration is available on the device. You'll see this in the debug logs; it'll tell you what is unsupported, and then in a video/audio debug listener you can see which codec was chosen.
>
>As a side note, if you need software decoders you can use:
>
>```       
>DefaultRenderersFactory rf = new DefaultRenderersFactory(this.getApplicationContext(), null, >DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);
>        player = ExoPlayerFactory.newSimpleInstance(
>                rf,
>                new DefaultTrackSelector(),
>                new DefaultLoadControl()
>        );
>```
>
>If you want to prefer the use of software decoders (i.e. ffmpeg for audio) just set the EXTENSION_RENDERER_MODE_ON to EXTENSION_RENDERER_MODE_PREFER

_Originally posted by @brandoncodes in https://github.com/google/ExoPlayer/issues/3039#issuecomment-315129051_

**Comment by icbaker** [comment]
The [ffmpeg extension README](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md#using-the-module) has details about how to use [`@DefaultRenderersFactory.ExtensionRendererMode`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.ExtensionRendererMode.html).

If you need more information than is provided there, please ask specific questions including detail about what you're trying to achieve and what isn't working or is behaving unexpectedly.

I'm going to close this, but you can still post specific follow-up questions and I can re-open it.

**Comment by sagarNapps10x** [comment]
I wanted to change the exo-player to use a software decoder

 so when I searched in the issue section I found this comment in this issue here https://github.com/google/ExoPlayer/issues/3039#issuecomment-315129051

in the comment, they have suggested changing the default renderers factory extension render mode to EXTENSION_RENDERER_MODE_PREFER 

so I wanted to know is this the way to change software decoder or Is there any other way of achieving it

thanks

**Comment by icbaker** [comment]
When you say 'software decoder' do you mean a decoder bundled with your app (i.e. not one provided by the platform) or do you mean any decoder implemented without hardware acceleration (i.e. both platform-provided decoders implemented only in software **and** all decoders bundled with your app)?

If it's the former, then the guidance I linked above is relevant and should give you the info you need.

If it's the latter then the answer is more complicated - but in this case it would be helpful to understand why you want to deliberately exclude using the hardware-accelerated platform decoders.

**Comment by sagarNapps10x** [comment]
I guess its the latter one

Its a requirement from our team side  like how this app : https://play.google.com/store/apps/details?id=com.playit.videoplayer&hl=en_IN&gl=US

they are changing decoders to software only in Android
