### ISSUE TITLE
MPEG1/2 not working on Samsung devices

### ISSUE THREAD

**Issue by dujovski** [google/ExoPlayer#9987]
I'm having some problems with MPEG1/2 (H222/H262) video codec on Samsung devices. I try to run the video via the ExoPlayer, but I got an error that the codec is unsupported. On Huawei, Xiaomi devices, videos are working well, but not on Samsung devices. Here is the log provided by the demo application. I am using FFmpeg for some audio problems, but for video codecs, I don't find anything that will help me with the mpeg2 codec. Can you help me?

`
exoplayer2.demo D/EventLogger:   Libgav1VideoRenderer []
exoplayer2.demo D/EventLogger:   MediaCodecVideoRenderer [
exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
exoplayer2.demo D/EventLogger:       [ ] Track:0, id=0, mimeType=video/mpeg2, res=720x576, supported=NO_UNSUPPORTED_TYPE
exoplayer2.demo D/EventLogger:     ]
exoplayer2.demo D/EventLogger:   ]
`

**Comment by icbaker** [comment]
Android devices are not required to support the codecs you listed. The full list of supported codecs is here: https://developer.android.com/guide/topics/media/media-formats#core

It's likely that some of your devices do support these codecs, and others don't - this is expected. If you want your content to work across all android devices I suggest re-encoding it to a supported format.

> I am using FFmpeg for some audio problems, but for video codecs, I don't find anything that will help me with the mpeg2 codec. Can you help me?

#2159 tracks implementing an `FfmpegVideoRenderer`.
