### ISSUE TITLE
Exoplayer 2.14.2 + Flussonic + HLS

### ISSUE THREAD

**Issue by ivostefanoff** [google/ExoPlayer#9988]
Hello,
I experienced randomly (after 2-3-4 hours of playback) drops of HLS streams made by Fllussonic with no  reason giver - just player stand  in IDLE due to some reason. Have somebody seen some similar issues?
Regards

**Comment by christosts** [comment]
We are not aware of any issues with such particular streams. If you need assistance with a specific problem, please provide the information described on the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

I'm closing this issue for now, feel free to re-open if you need further assistance.
