### ISSUE TITLE
HLS stream freezes/crashes intermittently 

### ISSUE THREAD

**Issue by benderzgreat** [google/ExoPlayer#9989]
----------------------------------------------------------------------------------------------------

- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue

Issues #5003 and then #5455 seem to be related to this issue, but not the exact behavior.

- Try playing problematic media in the demo app:
  http://exoplayer.dev/demo-application.html

I tried playing the stream in the demo exoplayer app loaded onto a chromecast device, 
with the same results as through our app.

_ExoPlayer Version for Demo App 2.16.1_
----------------------------------------------------------------------------------------------------

To reproduce the issue I will send a url with the manifest and needed http headers for playback in the browser to the 

'dev.exoplayer@gmail.com'

Another way to reproduce would be to use our non authenticated stream (https://pac-12.com/live?networks=P12I in web or on Pac12 Now mobile app) 

And cast the stream to a ChromeCast device. 

I tested with:      ChromeCast Model GZRNL
       - ANDROID TV OS VERSION: 10
       - KERNEL VERSION: 4.9.180
       - TV OS BUILD: QTS1.210311.036.7814738

Within an hour(usually about 20-30 minutes) the stream will buffer/freeze for a second and then crash at totally random times.

Only sometimes a 102 encoding parameter ERROR will come up, but even after checking with the parameters stated in the chromecast sdk I was unable to stop from crashing.

The stream also plays fine on every other platform, it will even play without crashing on the native ChromeCast app.

I tested many different renditions and changes to the stream and even in the cases where it did not crash I saw some version of this right before the crash:

`02-16 17:34:35.349  3775  8633 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
02-16 17:34:35.349  3775  8633 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
02-16 17:34:35.349  3775  8633 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
02-16 17:34:35.349  3775  8633 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome2, width 1920, height 1088 nBufferCountMin:4
02-16 17:34:35.349  3775  3841 D OmxVideoDecoder: getConfig 2040 0x700000f
02-16 17:34:35.350  3775  3841 D OmxVideoDecoder: getConfig 2043 nIndex 0x700000f
02-16 17:34:35.350  3775  3841 D OmxVideoDecoder: getConfig OMX_IndexConfigCommonOutputCrop pRect->nWidth=416, pRect->nHeight=234
02-16 17:34:35.350  3775  3841 D OmxVideoDecoder: setConfig 2160 0x7f00000c
02-16 17:34:35.351  3775  8633 D OmxVideoDecoder: getConfig 2040 0x7f00000c
02-16 17:34:35.351  3775  8633 D OmxVideoDecoder: getConfig 2040 0x7f00000c
02-16 17:34:35.351  3775  8633 E OMXNodeInstance: getConfig(0xe7b296cc:amlogic.avc.decoder.awesome2, ??(0x7f00000c)) ERROR: UnsupportedSetting(0x80001019)

02-17 15:31:47.111  3775  3775 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
02-17 15:31:47.111  3775  3775 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1080..
02-17 15:31:47.112  3775  3775 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1080
02-17 15:31:47.112  3775  3775 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome2, width 1920, height 1080 nBufferCountMin:4
02-17 15:31:47.112  3775  3844 D OmxVideoDecoder: getConfig 2040 0x700000f
02-17 15:31:47.112  3775  3844 D OmxVideoDecoder: getConfig 2043 nIndex 0x700000f
02-17 15:31:47.112  3775  3844 D OmxVideoDecoder: getConfig OMX_IndexConfigCommonOutputCrop pRect->nWidth=1920, pRect->nHeight=1080
02-17 15:31:47.112  3775  3775 D OmxVideoDecoder: setConfig 2160 0x7f00000c
02-17 15:31:47.113  3775  4152 D OmxVideoDecoder: getConfig 2040 0x7f00000c
02-17 15:31:47.113  3775  4152 D OmxVideoDecoder: getConfig 2040 0x7f00000c
02-17 15:31:47.113  3775  4152 E OMXNodeInstance: getConfig(0xf5a296cc:amlogic.avc.decoder.awesome2, ??(0x7f00000c)) ERROR: UnsupportedSetting(0x80001019)`

From what I can tell this is referencing a vendor specific OMX param error.

'OMXNodeInstance: getConfig(0xf5a296cc:amlogic.avc.decoder.awesome2, ??(0x7f00000c)) ERROR: UnsupportedSetting(0x80001019)'

But I have been unable to tell what the indexes represent.

When I check the resolution of the 1080 TS file in any media player or any media information tool it reads as 1920x1080. But when I look at the macroblocks:

`[NULL @ 0x7f85f862ad40] Opening 'segment0.ts' for reading
[file @ 0x7f85f862b1c0] Setting default whitelist 'file,crypto,data'
[mpegts @ 0x7f85f862ad40] Format mpegts probed with size=2048 and score=50
[mpegts @ 0x7f85f862ad40] stream=0 stream_type=1b pid=1e1 prog_reg_desc=CUEI
[mpegts @ 0x7f85f862ad40] stream=1 stream_type=f pid=1ec prog_reg_desc=CUEI
[mpegts @ 0x7f85f862ad40] stream=3 stream_type=15 pid=1f6 prog_reg_desc=CUEI
[mpegts @ 0x7f85f862ad40] Before avformat_find_stream_info() pos: 0 bytes read:32768 seeks:0 nb_streams:4
[mpegts @ 0x7f85f862ad40] parser not found for codec timed_id3, packets or times may be invalid.
[h264 @ 0x7f85f862bec0] ct_type:0 pic_struct:0
[extract_extradata @ 0x7f85f8638e40] nal_unit_type: 9(AUD), nal_ref_idc: 0
[extract_extradata @ 0x7f85f8638e40] nal_unit_type: 7(SPS), nal_ref_idc: 1
[extract_extradata @ 0x7f85f8638e40] nal_unit_type: 8(PPS), nal_ref_idc: 1
[extract_extradata @ 0x7f85f8638e40] nal_unit_type: 6(SEI), nal_ref_idc: 0
    Last message repeated 2 times
[extract_extradata @ 0x7f85f8638e40] nal_unit_type: 5(IDR), nal_ref_idc: 1
[h264 @ 0x7f85f862bec0] nal_unit_type: 9(AUD), nal_ref_idc: 0
[h264 @ 0x7f85f862bec0] nal_unit_type: 7(SPS), nal_ref_idc: 1
[h264 @ 0x7f85f862bec0] nal_unit_type: 8(PPS), nal_ref_idc: 1
[h264 @ 0x7f85f862bec0] nal_unit_type: 6(SEI), nal_ref_idc: 0
    Last message repeated 2 times
[h264 @ 0x7f85f862bec0] nal_unit_type: 5(IDR), nal_ref_idc: 1
[h264 @ 0x7f85f862bec0] Format yuv420p chosen by get_format().
[h264 @ 0x7f85f862bec0] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 0x7f85f862bec0] ct_type:0 pic_struct:0
[h264 @ 0x7f85f862bec0] no picture 
[h264 @ 0x7f85f862bec0] ct_type:0 pic_struct:0
    Last message repeated 34 times
[mpegts @ 0x7f85f862ad40] probing stream 1 pp:2500
[mpegts @ 0x7f85f862ad40] Probe with size=1458, packets=1 detected aac with score=51
[mpegts @ 0x7f85f862ad40] probed stream 1
[h264 @ 0x7f85f862bec0] ct_type:0 pic_struct:0
    Last message repeated 59 times
[mpegts @ 0x7f85f862ad40] parser not found for codec timed_id3, packets or times may be invalid.
[h264 @ 0x7f85f862bec0] ct_type:0 pic_struct:0
    Last message repeated 56 times
[mpegts @ 0x7f85f862ad40] max_analyze_duration 5000000 reached at 5000000 microseconds st:0
[mpegts @ 0x7f85f862ad40] start time for stream 2 is not set in estimate_timings_from_pts
[mpegts @ 0x7f85f862ad40] After avformat_find_stream_info() pos: 0 bytes read:3362960 seeks:2 frames:321
Input #0, mpegts, from 'segment0.ts':
  Duration: 00:00:06.01, start: 11284.674044, bitrate: 4780 kb/s
  Program 1 
  Stream #0:0[0x1e1], 152, 1/90000: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, progressive, left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 0/1, Closed Captions, 30 fps, 30 tbr, 90k tbn
  Stream #0:1[0x1ec](eng), 168, 1/90000: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
  Stream #0:2[0x1f4], 0, 1/90000: Data: scte_35, 0/1
  Stream #0:3[0x1f6], 1, 1/90000: Data: timed_id3 (ID3  / 0x20334449), 0/1`

I can see that it does show 1920x1088, I know that due mod16 this is necessary and in most cases the extra bits are just padded and can be dropped or ignored by most encoders. Could this be causing an issue?

[bugtest.log](https://github.com/google/ExoPlayer/files/8100794/bugtest.log)

Thanks

**Comment by benderzgreat** [comment]
https://github.com/google/ExoPlayer/issues/1894
Seems to be somewhat related to this issue.

I did some more digging through the files and it seems like the error relates to either the:

OMX_IndexConfigCommonOutputCrop or OMX_IndexConfigStreamInterlaceFormat

When looking at the OMX IL, it appears the issue could have to do with interlacing.

4.2.49 OMX_STREAMINTERLACEFORMATTYPE: fig 4-7 (see attached pdf)


When I compared segments from two different renditions I did see this:

`Stream #0:0[0x1e1], 152, 1/90000: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive, left), 416x234 (416x240) [SAR 1:1 DAR 16:9], 0/1, Closed Captions, 30 fps, 30 tbr, 90k tbn`

`Stream #0:0[0x1e1], 152, 1/90000: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, progressive, left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 0/1, Closed Captions, 30 fps, 30 tbr, 90k tbn`

Could the addition/subtraction of the bt709 param be causing the issue?

**Comment by christosts** [comment]
When I test the stream, I get an HTTP 405 (with the headers set). Are the headers still valid?

**Comment by benderzgreat** [comment]
Sorry, it may have expired.

These should work

ca=eyJhbGciOiJIUzI1NiJ9.eyJwTVZQRCI6IlByb3h5TVZQRF9NYXNzaWxvbiIsIk1WUEQiOiJwYWMxMmVudGVycHJpc2VzIiwic3ViIjoiUGFjMTJTdHJlYW0iLCJpc3MiOiJQQUMxMiIsImlhdCI6MTY0NTYzMjY4OCwianRpIjoiMWQyZmE0ZDQ2NTkyM2QxODI0N2U5ZGZjODgxMjdjZTEiLCJleHAiOjE2NDYwNTI2ODh9.BX4KmMaaLNXvb56JuqzZqDKAdiEf4TcMHGSWU6W1wnc

p12sid=46b84af0-8f3e-11ec-b1e7-9d7fea75ce63

**Comment by christosts** [comment]
They don't work for me again. May I ask you share a code snippet how you're passing them? Our DataSource APIs accept headers in a key-value form and we can only set one `Cookie` header, so I concatenated the two values with `; ` (note the space after `;`)

```
ImmutableMap<String, String> headers = ImmutableMap.of(
"Cookie","ca=eyJhbGciOiJIUzI1NiJ9.eyJwTVZQRCI6IlByb3h5TVZQRF9NYXNzaWxvbiIsIk1WUEQiOiJwYWMxMmVudGVycHJpc2VzIiwic3ViIjoiUGFjMTJTdHJlYW0iLCJpc3MiOiJQQUMxMiIsImlhdCI6MTY0NTYzMjY4OCwianRpIjoiMWQyZmE0ZDQ2NTkyM2QxODI0N2U5ZGZjODgxMjdjZTEiLCJleHAiOjE2NDYwNTI2ODh9.BX4KmMaaLNXvb56JuqzZqDKAdiEf4TcMHGSWU6W1wnc; p12sid=46b84af0-8f3e-11ec-b1e7-9d7fea75ce63");
httpDataSourceFactory.setDefaultRequestProperties(headers);
```

and I also tried updating the stream's value for the `p12sid` parameter

**Comment by benderzgreat** [comment]
curl -H "Cookie: ca=eyJhbGciOiJIUzI1NiJ9.eyJwTVZQRCI6IlByb3h5TVZQRF9NYXNzaWxvbiIsIk1WUEQiOiJwYWMxMmVudGVycHJpc2VzIiwic3ViIjoiUGFjMTJTdHJlYW0iLCJpc3MiOiJQQUMxMiIsImlhdCI6MTY0NTYzMjY4OCwianRpIjoiMWQyZmE0ZDQ2NTkyM2QxODI0N2U5ZGZjODgxMjdjZTEiLCJleHAiOjE2NDYwNTI2ODh9.BX4KmMaaLNXvb56JuqzZqDKAdiEf4TcMHGSWU6W1wnc; p12sid=46b84af0-8f3e-11ec-b1e7-9d7fea75ce63" "https://p12n.pac-12.com/v1/master/b6988789cc420a523cc8393d9c7e629c76fece84/p12n_2019_11/index.m3u8?ads.caid=&ads.csid=national&ads.device=desktop&ads.deviceos=web&ads.fwvcid2=f75f53d0-8e8f-11ec-90ed-61516d09f18c&ads.p12sid=46b84af0-8f3e-11ec-b1e7-9d7fea75ce63" 


this works for me, fixed the link

**Comment by benderzgreat** [comment]
Also, I was able to find these messages I haven't seen before in the logs.

02-18 16:46:38.514 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(40)] MediaEvent: {"debug":"Audio buffer splice at PTS=868177329us. Trimmed tail of overlapped buffer (PTS=868170662us) by 14667us."}
02-18 16:46:46.539 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(40)] MediaEvent: {"debug":"Skipping audio splice trimming at PTS=874214661us. Found only 1us of overlap, need at least 1000us. Multiple occurrences may result in loss of A/V sync."}
02-18 16:46:49.571  3771  3840 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
02-18 16:46:49.571  3771  3840 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
02-18 16:46:49.571  3771  3840 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
02-18 16:46:49.571  3771  3840 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome2, width 1920, height 1088 nBufferCountMin:4
02-18 16:46:49.572  3771  4172 D OmxVideoDecoder: getConfig 2040 0x700000f
02-18 16:46:49.572  3771  4172 D OmxVideoDecoder: getConfig 2043 nIndex 0x700000f
02-18 16:46:49.572  3771  4172 D OmxVideoDecoder: getConfig OMX_IndexConfigCommonOutputCrop pRect->nWidth=1920, pRect->nHeight=1080
02-18 16:46:49.572  3771  4172 D OmxVideoDecoder: setConfig 2160 0x7f00000c
02-18 16:46:49.572  3771  3840 D OmxVideoDecoder: getConfig 2040 0x7f00000c
02-18 16:46:49.573  3771  4172 D OmxVideoDecoder: getConfig 2040 0x7f00000c
02-18 16:46:49.573  3771  4172 E OMXNodeInstance: getConfig(0xf42296cc:amlogic.avc.decoder.awesome2, ??(0x7f00000c)) ERROR: UnsupportedSetting(0x80001019)
02-18 16:46:49.573  3771  3840 D OmxVideoDecoder: getConfig 2040 0x7f000009
02-18 16:46:49.573  3771  4172 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.573  3771  4172 V OmxVideoDecoder: VendorExt: getConfig: index=0 (4k-osd)
02-18 16:46:49.573  3771  3840 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.573  3771  3840 V OmxVideoDecoder: VendorExt: getConfig: index=1 (video-trickmode)
02-18 16:46:49.573  3771  3771 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.573  3771  3771 V OmxVideoDecoder: VendorExt: getConfig: index=2 (is-mvc)
02-18 16:46:49.574  3771  3771 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.574  3771  3771 V OmxVideoDecoder: VendorExt: getConfig: index=3 (is-flv)
02-18 16:46:49.574  3771  3840 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.574  3771  3840 V OmxVideoDecoder: VendorExt: getConfig: index=4 (dvconfig-box)
02-18 16:46:49.574  3771  3771 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.574  3771  3771 V OmxVideoDecoder: VendorExt: getConfig: index=5 (profile-level)
02-18 16:46:49.575  3771  3771 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.575  3771  3771 V OmxVideoDecoder: VendorExt: getConfig: index=5 (profile-level)
02-18 16:46:49.575  3771  3840 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.575  3771  3840 V OmxVideoDecoder: VendorExt: getConfig: index=6 (nrdp)
02-18 16:46:49.575  3771  3771 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.575  3771  3771 V OmxVideoDecoder: VendorExt: getConfig: index=7 (low-latency)
02-18 16:46:49.575  3771  4172 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.575  3771  4172 V OmxVideoDecoder: VendorExt: getConfig: index=8 (save-mem)
02-18 16:46:49.576  3771  3840 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.576  3771  3840 V OmxVideoDecoder: VendorExt: getConfig: index=9 (videoLayer)
02-18 16:46:49.576  3771  4172 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.576  3771  4172 V OmxVideoDecoder: VendorExt: getConfig: index=10 (renderByOmx)
02-18 16:46:49.576  3771  3840 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:49.576  3771  3840 V OmxVideoDecoder: VendorExt: getConfig: index=11 (McodecReport)
02-18 16:46:49.576  3771  3840 D OmxVideoDecoder: mMcodecReport=0 mPeer.get=-198803456
02-18 16:46:49.576  3771  4172 D OmxVideoDecoder: getConfig 2040 0x6f100004
02-18 16:46:53.119  3613  3613 E FrameEvents: addLatch: Did not find frame.
02-18 16:46:53.119  3613  3613 E FrameEvents: addPreComposition: Did not find frame.
02-18 16:46:53.897 12286 12312 I v8      : [12286:0xd95ca4c0]  2311925 ms: Scavenge 9.3 (11.4) -> 8.9 (11.4) MB, 1.0 / 0.0 ms  (average mu = 0.997, current mu = 0.998) allocation failure 
02-18 16:46:53.907 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(38)] MediaEvent: {"error":"Parsed buffers not in DTS sequence"}
02-18 16:46:53.908 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(38)] MediaEvent: {"error":"Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf"}
02-18 16:46:53.909 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(38)] MediaEvent: {"error":"Parsed buffers not in DTS sequence"}
02-18 16:46:53.910 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":16}
02-18 16:46:53.911 12286 13060 I chromium: [12286:13060:INFO:batching_media_log.cc(40)] MediaEvent: {"event":"kPipelineStateChange","pipeline_state":"kStopping"}
02-18 16:46:53.912 12286 12312 I chromium: [12286:12312:INFO:html_media_element.cc(2624)] pause(0x41e662e8)
02-18 16:46:53.913 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(40)] MediaEvent: {"event":"kPause"}
02-18 16:46:53.917 12286 13060 I chromium: [12286:13060:INFO:batching_media_log.cc(40)] MediaEvent: {"event":"kPipelineStateChange","pipeline_state":"kStopped"}
02-18 16:46:53.917  5147  5939 D         : PlayerBase::stop() from IPlayer
02-18 16:46:53.917  5147  5939 D AudioTrack: stop(27): called with 18733060 frames delivered
02-18 16:46:53.929 12264 12345 W cr_MediaCodecBridge: Releasing: OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.930  3771 13082 I OmxComponent: OMX_CommandStateSet 806 Cmd 0 nParam1 0x2
02-18 16:46:53.930  3771 13082 I OmxComponent: STATE_SET:   OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.930  3771 13082 I OmxComponent: OMX.amlogic.avc.decoder.awesome2: flush input
02-18 16:46:53.930  3771 13082 V AmlogicVideoDecoderAwesome: flushInput:1036 >
02-18 16:46:53.930  3771 13082 V OMX_WorkerPeer: vendor/omx/omx_framework/WorkerPeer.cpp:flushInput:56 --------------------
02-18 16:46:53.930  3771 13082 V AmlogicVideoDecoderAwesome: pause:313 >
02-18 16:46:53.931  3771 13082 D AmlogicVideoDecoderAwesome: mVideo mDisplayTread stop
02-18 16:46:53.933  3771 13082 V AmlogicVideoDecoderAwesome: reset:384 >
02-18 16:46:53.933  3771 13082 D AmlogicVideoDecoderAwesome: reset_1
02-18 16:46:53.933  3771 13082 I amcodec : AMSTREAM_SET_OMX_RUNNING ret=0
02-18 16:46:53.946 12286 12312 I chromium: [12286:12312:INFO:media_source.cc(418)] removeSourceBuffer this=0x3a436d50 buffer=0x52f42e20
02-18 16:46:53.947 12286 12312 I chromium: [12286:12312:INFO:html_media_element.cc(645)] parseAttribute(0x41e662e8, kSrcAttr, old="blob:https://pac-12.com/fa3e31ae-b937-40d5-996b-fa36d3fe9e11", new=<null>)
02-18 16:46:53.947 12286 12312 I chromium: [12286:12312:INFO:html_media_element.cc(862)] load(0x41e662e8)
02-18 16:46:53.948 12286 12312 I chromium: [12286:12312:INFO:batching_media_log.cc(40)] MediaEvent: {"event":"kWebMediaPlayerDestroyed"}
02-18 16:46:53.951  5147  5147 I chromium: [5147:5147:INFO:web_application.cc(1137)] [1e3ccdca] Media is now paused for app_id=30831990
02-18 16:46:53.951  5147  5147 I chromium: [5147:5147:INFO:media_trait_handler_impl.cc(557)] Playback has stopped.
02-18 16:46:53.953  3529  4285 I MediaFocusControl: abandonAudioFocus() from uid/pid 10041/5147 clientId=android.media.AudioManager@a130beborg.chromium.content.browser.AudioFocusDelegate@2e2b026
02-18 16:46:53.954  5147  5147 I chromium: [5147:5147:INFO:auto_volume.cc(512)] New playing state for app 30831990: 0
02-18 16:46:53.954  5147  5147 I chromium: [5147:5147:INFO:cast_media_blocker.cc(81)] MediaSessionInfoChanged media_loading_blocked=0 media_starting_blocked=0 is_suspended=1 is_controllable=0 paused_by_user=0
02-18 16:46:53.959  3771 13082 I amcodec : [codec_reset:1127]ret=0
02-18 16:46:53.959  3771 13082 D AmlogicVideoDecoderAwesome: reset_2
02-18 16:46:53.959  3771 13082 D AmlogicVideoDecoderAwesome: mVideo mDisplayTread start
02-18 16:46:53.959  3771 13082 D AmlogicVideoDecoderAwesome: mDTaskStatus=0
02-18 16:46:53.960  3771 13082 V AmlogicVideoDecoderAwesome: start:321 >
02-18 16:46:53.960  3771 13082 E ThreadWorker: pthread on exit wait clean
02-18 16:46:53.960  3771 13082 D AmlogicVideoDecoderAwesome: mVideo start
02-18 16:46:53.960  3771 13082 V AmlogicVideoDecoderAwesome: flushInput:1069 >
02-18 16:46:53.960  3771 13082 I OmxComponent: OMX.amlogic.avc.decoder.awesome2: flush output
02-18 16:46:53.961  3771 13082 V AmlogicVideoDecoderAwesome: flushOutput:1072 >
02-18 16:46:53.961  3771 13082 D AmlogicVideoDecoderAwesome: displayThread__flushOutput__fillBufferDone
02-18 16:46:53.961  3771 13082 V AmlogicVideoDecoderAwesome: flushOutput:1126 >
02-18 16:46:53.961  3771 13082 D AmlogicVideoDecoderAwesome: mVideo stop
02-18 16:46:53.962  3771 13082 V AmlogicVideoDecoderAwesome: stop:363 >
02-18 16:46:53.962  3771 13293 V OMX_WorkerPeer: vendor/omx/omx_framework/WorkerPeer.cpp:runWorkerStatic:154 --------------------
02-18 16:46:53.962  3771 13293 V OMX_WorkerPeer: vendor/omx/omx_framework/WorkerPeer.cpp:runWorker:160 --------------------
02-18 16:46:53.962  3771 13082 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.962  3771 13082 I chatty  : uid=1046(mediacodec) ecoder.awesome2 identical 3 lines
02-18 16:46:53.962  3771 13082 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.962  3771 13082 I OmxComponent: STATE_DONE:  OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.963  3771 13082 I OmxComponent: OMX_CommandStateSet 806 Cmd 0 nParam1 0x1
02-18 16:46:53.964  3771 13082 I OmxComponent: STATE_SET:   OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.964  3771 13082 V AmlogicVideoDecoderAwesome: releaseResources:427 >
02-18 16:46:53.964  3771 13082 V AmlogicVideoDecoderAwesome: tearDown:921 >
02-18 16:46:53.964  3771 13082 V AmlogicVideoDecoderAwesome: tearDown:1627 >
02-18 16:46:53.964  3771 13082 V AmlogicVideoDecoderAwesome: initializeState_l:1725 >
02-18 16:46:53.967  3771 13082 D AmlogicVideoDecoderAwesome: free v4lvideo device instance ID:0
02-18 16:46:53.967  3771 13082 V AmlogicVideoDecoderAwesome: disable osd video ...-198802736
02-18 16:46:53.968  3771 13082 I OmxComponent: STATE_TRANS: OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.968  3771 13082 I OmxComponent: STATE_TRANS: OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.971  3771 13082 I OmxComponent: STATE_DONE:  OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.972  3771  3840 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=1, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.972  3771  3840 I omx_core: OMX_freeHandle_num_= 0
02-18 16:46:53.972  3771  3840 D OmxComponent: ~OmxComponent 248 : OMX.amlogic.avc.decoder.awesome2
02-18 16:46:53.972  3771  3840 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
02-18 16:46:53.972  3771  3840 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
02-18 16:46:53.972  3771  3840 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder, mOmxInstancenum 0

**Comment by christosts** [comment]
> curl -H "Cookie: ca=eyJhbGciOiJIUzI1NiJ9.eyJwTVZQRCI6IlByb3h5TVZQRF9NYXNzaWxvbiIsIk1WUEQiOiJwYWMxMmVudGVycHJpc2VzIiwic3ViIjoiUGFjMTJTdHJlYW0iLCJpc3MiOiJQQUMxMiIsImlhdCI6MTY0NTYzMjY4OCwianRpIjoiMWQyZmE0ZDQ2NTkyM2QxODI0N2U5ZGZjODgxMjdjZTEiLCJleHAiOjE2NDYwNTI2ODh9.BX4KmMaaLNXvb56JuqzZqDKAdiEf4TcMHGSWU6W1wnc; p12sid=46b84af0-8f3e-11ec-b1e7-9d7fea75ce63" "https://p12n.pac-12.com/v1/master/b6988789cc420a523cc8393d9c7e629c76fece84/p12n_2019_11/index.m3u8?ads.caid=&ads.csid=national&ads.device=desktop&ads.deviceos=web&ads.fwvcid2=f75f53d0-8e8f-11ec-90ed-61516d09f18c&ads.p12sid=46b84af0-8f3e-11ec-b1e7-9d7fea75ce63"
> 
> this works for me, fixed the link

This still returns HTTP 405 for me. Is the content geo-restricted?

**Comment by benderzgreat** [comment]
Yes, I will send a url to the dev email to get the manifest before the cdn.
