### ISSUE TITLE
Loading video from obb file

### ISSUE THREAD

**Issue by mjsibbald** [google/ExoPlayer#999]
I've been cracking my head on this. 

I'm trying to load a video from a obb, I thought using the "content://" url scheme would get me there. 
But all I'm getting is file not found. 

How would a url using this "content://" look like. And 2 is this the way to go anyways. 

Thanks you.

**Comment by ojw28** [comment]
I don't think content:// URIs are the right thing to be using. What format is the obb file as a whole? Assuming you're needing (or will need) to deliver more than one asset, the obb file will have to be something other than just the video file, I think. Is it a zip file, or something else?

Did you read through [this](http://developer.android.com/google/play/expansion-files.html), which seems to contain quite a lot of relevant information? It looks like an obb is just a regular file, which would have a file:// URI. So the question is more about the format of the obb file as a whole, and how you'd read just the asset that you're interested in from it.

**Comment by mjsibbald** [comment]
no just one asset in a uncompressed obb. 1 video file.
I've been trying the file:// but or... I dont have the right path or this is not possible...
file:///storage/emulated/0/Android/obb/app_packagename/main.1.packagename.obb/videoname.mp4

results in:
java.io.FileNotFoundException: /storage/emulated/0/Android/obb/app_packagename/main.1.packagename.obb/obb/videoname.mp4 

But that obb is def. there!

obb is the folder name in the zip/obb

**Comment by ojw28** [comment]
I don't understand what you mean when you say the video is in an uncompressed obb. An obb isn't a file format or a container for other files. Either the obb file *is* the video file, or the obb file is in some format like zip that allows you to hold multiple files. If the obb file is the video file, then I would expect a regular file URI to work. The URI would just be that of the obb file directly though (I wouldn't expect to see `/videoname.mp4` on the end).

**Comment by mjsibbald** [comment]
obb is the format used for expansion files, which is basically a zip file (uncompressed).

in it, it has a folder "obb" containing 1 video file.

**Comment by ojw28** [comment]
Oh right. The documentation is a little confusing. You're allowed to use any file type at all for apk expansion files. The files are always renamed to end in `obb`. Separately, there's an `obb` file format, and you can create such files using the `jobb` tool.

So I think what you're saying is that you've created a file using the `jobb` tool that contains a single media file? Is that correct? Presumably you'd have to mount your file using the [StorageManager](http://developer.android.com/reference/android/os/storage/StorageManager.html) API in order to read the files from within it? Are you doing that?

**Comment by mjsibbald** [comment]
its basically a uncompressed zip renamed to obb. it was working when using with Mediaplayer, but we switch to exoplayer. 

We've been able to load the "content://" with  APEZProvider. (declared in the manifest and using when building the "content://"). 

Now it doesn't give use any errors or feedback, but it's not playing either. When we use a filename thats not in the obb. it fails and show an error. 

So it looks like it can find the file, but is simply not playing it. 

Maik

**Comment by mjsibbald** [comment]
Well turns out it stuck at preparing state. It's not playing because ready is never fired. 

Any ideas?

**Comment by mjsibbald** [comment]
Just updated to the latest version of Exoplayer and its stuck at "idle" instead of preparing.

**Comment by ojw28** [comment]
I was able to play a file within an obb file using my suggestion above (use StorageManager). I did the following:

1. Created an obb file using jobb
1. Pushed the obb file onto the device
1. Mounted it in application code using `StorageManager.mountObb`
1. When the callback indicates that mounting was successfull, get the mounted path using `StorageManager.getMountedObbPath`, which looks similar to `/mnt/obb/d568994e6ad66a21e8531fa8375da0de`.
1. Construct a file URI that looks like `file://<mounted-obb-path>/path/to/media/in/obb/media.ext`, and use it.

**Comment by mjsibbald** [comment]
Yeah me too, using the jobb tool. Unfortunately I cant get passed the 512 MB....But at least I've got something. 

If you are using anything else, please let me know. I've tried: jObbifier.... but its doesn't mount permission denied. 
Thanks for the help!

**Comment by ojw28** [comment]
A permission denied error doesn't sound related to how you create the obb file. Are you running Marshmallow on your test device by any chance?

**Comment by mjsibbald** [comment]
No 5.1.1, and when I use jobb it mounts. But with jObbifier it doesn't. So my guess thats the problem. neet to find a way to get passed 512.

**Comment by ojw28** [comment]
Taking a step back, I don't really understand what you're trying to do. Why are you putting a single media file inside an obb in the first place, rather than just using the media file directly?

**Comment by mjsibbald** [comment]
I cant push beyond 50nb to the playstore. So I need to use expansion packs.

**Comment by ojw28** [comment]
According to [this](http://developer.android.com/google/play/expansion-files.html) page about expansion files, you can use whatever file format you want:
```Each expansion file you upload can be any format you choose (ZIP, PDF, MP4, etc.)```

**Comment by aliasgarlabs** [comment]
@ojw28 I'm having trouble playing mp3 from obb. 

> I was able to play a file within an obb file using my suggestion above (use StorageManager). I did the following:

>Created an obb file using jobb.
>Pushed the obb file onto the device.
>Mounted it in application code using StorageManager.mountObb.
>When the callback indicates that mounting was successfull, get the mounted path using >StorageManager.getMountedObbPath, which looks similar to >/mnt/obb/d568994e6ad66a21e8531fa8375da0de.
>Construct a file URI that looks like file://<mounted-obb-path>/path/to/media/in/obb/media.ext, and >use it.

I read this comment of yours. Do you care to explain after mounting, how did you **use it**? Thanks :)
