### ISSUE TITLE
Getting 403 on this specific stream

### ISSUE THREAD

**Issue by lpv-1902** [google/ExoPlayer#9992]
Hi, this particular stream is getting a 403 response from Exoplayer. This is currently working on desktop browsers with HLS + M3U8 extension and Safari.

https://midas.fubo.tv/v1/master/6c9193257c0eed8ca3f1eabccc4444f9477500f1/production/v4/master.m3u8?ads._fw_station=832870001&ads._fw_vcid2=fuboTV%3A5baa553bbc95d34417f166ff&ads.fw_nw_id=393638&hdnts=ip%3D208.82.163.153~st%3D1645419479~exp%3D1645505879~acl%3D%2F%2A~data%3D1645505879~hmac%3Ddcd06b43bb3f2c1993ef9901130c0db742a746c82a12cb549c18511d6d2d5069&watchToken=eyJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6IlVzYUJhc2VXYXRjaFRva2VuIiwidHlwIjoiSldUIn0.eyJ3YXRjaFRva2VuIjp7ImNhbGxTaWduIjoiQkxPT01QTCIsImRldmljZSI6IkFMTCIsImJhbmR3aWR0aCI6Ik1BU1RFUiIsImNvdW50cnkiOiJVU0EiLCJ1c2VySWQiOiI1YmFhNTUzYmJjOTVkMzQ0MTdmMTY2ZmYiLCJyZXF1ZXN0VHlwZSI6ImxpdmUiLCJyZWdpb24iOiJ3ZXN0In0sImhvbWVaaXAiOiI5MDAxNCIsImdlb1ppcCI6IjM2NTI2In0.l1aDaEoTulzvbagNTb64S6LuV7p_AOF-Ep5Ckj-pxKg

**Comment by christosts** [comment]
I'm getting an HTTP 504 when trying to open the content link from a Chrome or a command line http client like `curl` or `wget`. Often, these issues are related to setting a user agent in HTTP requests. If you are using the [demo app](https://exoplayer.dev/demo-application.html), you can quickly verify by calling `setUserAgent()` either on the `CronetDataSource.Factory` [here](https://github.com/google/ExoPlayer/blob/r2.16.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L101), or on the `DefaultHttpDataSource.Factory` [here](L109), depending if in the demo app you are using Cronet or not, and set a user agent that the server accepts.

If that solves the problem, please see instructions how to [customize the player](https://exoplayer.dev/customization.html#player-customization) to use the correct user agent in your app.
