### ISSUE TITLE
Unable to Render Video on Window Subsystem for Android after running ffmpeg on file.

### ISSUE THREAD

**Issue by adfwhitestar** [google/ExoPlayer#9994]
When running Exoplayer on Windows Subsystem for Android 1.8.32836.0 and 1.8.32837.0 (we have tried both) we are unable to render videos (Audio plays just fine) that are compressed and trancoded. We are using iOS's default UIImagePicker video compressor for Apple devices and one of Two Different Libraries from the Android Ecosystem for Android Devices, MP4Composer (https://github.com/MasayukiSuda/Mp4Composer-android) and SSffmpegVideoOperation (https://github.com/SimformSolutionsPvtLtd/SSffmpegVideoOperation) to try and compress video for transport and playing on other Android Devices. 

This works perfectly on a Physical Android Device such as All Pixel Devices, Samsung Devices, Sony Devices ect. But the video does not render on the Windows Subsystem for Android. Yes I am aware this is still in beta and is being worked on but was curious if there is anything that can be done as a fallback. 

When creating videos to view from Android
We are primarily using SSffmpegVideoOperation and calling the compress method to create a file for Exoplayer to play. 

Sample Repo: https://github.com/adfwhitestar/ExoplayerIssueWSA

- One Activity to Open the Exoplayer with a Video played from the raw folder that has already been run through the compression.
- One Activiiy to Open in VideoView with the same video
- One Activity to Open a stripped down version of the FFMpeg Compressor that is being used and convience buttons to open the ExoplayerActivity to show that it works before compress but not after. 
  1. The Compression Activity allows you to open and select a video on the file system. 
    a. I would normally install Google Photos and download a video from there to then compress and play.
    b. On the File Compression Screen there are 5 buttons File Select, Compress, Open original file in Exo player, Open Compressed File in Exo Player
      b1. File Select: allows you to select a file from the OS 
      b2. Compress: Runs FFMpeg compression query from SSffmpegVideoOperation 
      b3. Open original file in Exo player: Opens ExoPlayerActivity pointing at the Original File (To show that Exoplayer does work on WSA)
      b4. Open Compressed File in Exo Player: Opens ExoPlayerAcitiviy pointing at the Compressed File

The only reason that I am writing a bug in the ExoPlayer repo instead of the SSffmpegVideoOperation is that this process works on Physical Android Devices but, not on Windows Subsystem for Android. 

I have also pulled Codecs from Devices we have tested: 

======== Works
Pixel 2XL - Android 11

D/CODECS: OMX.qcom.video.decoder.avc, OMX.qcom.video.decoder.avc.secure, OMX.qcom.video.decoder.h263, OMX.qcom.video.decoder.hevc, OMX.qcom.video.decoder.hevc.secure, OMX.qcom.video.decoder.mpeg4, OMX.qcom.video.decoder.vp8, OMX.qcom.video.decoder.vp9, OMX.qcom.video.decoder.vp9.secure, OMX.qcom.video.encoder.avc, OMX.qcom.video.encoder.h263, OMX.qcom.video.encoder.hevc, OMX.qcom.video.encoder.mpeg4, OMX.qcom.video.encoder.vp8, c2.android.av1.decoder, c2.android.avc.decoder, OMX.google.h264.decoder, c2.android.avc.encoder, OMX.google.h264.encoder, c2.android.h263.decoder, OMX.google.h263.decoder, c2.android.h263.encoder, OMX.google.h263.encoder, c2.android.hevc.decoder, OMX.google.hevc.decoder, c2.android.hevc.encoder, c2.android.mpeg4.decoder, OMX.google.mpeg4.decoder, c2.android.mpeg4.encoder, OMX.google.mpeg4.encoder, c2.android.vp8.decoder, OMX.google.vp8.decoder, c2.android.vp8.encoder, OMX.google.vp8.encoder, c2.android.vp9.decoder, OMX.google.vp9.decoder, c2.android.vp9.encoder, OMX.google.vp9.encoder

Generic Android Emulator api 29
D/CODECS: OMX.google.h264.decoder, OMX.google.h263.decoder, OMX.google.hevc.decoder, OMX.google.mpeg4.decoder, OMX.google.vp8.decoder, OMX.google.vp9.decoder, OMX.google.h264.encoder, OMX.google.h263.encoder, OMX.google.mpeg4.encoder, OMX.google.vp8.encoder

======== Does not work
Windows Subsystem for Android 1.8.32836.0 and 1.8.32837.0
D/CODECS: OMX.google.h264.decoder, OMX.google.vp8.decoder, OMX.google.vp9.decoder, OMX.google.h264.encoder, OMX.google.vp8.encoder

Side Note: 
I have noticed that OMX.google.h263.decoder, OMX.google.hevc.decoder, OMX.google.mpeg4.decoder, OMX.google.h263.encoder, OMX.google.mpeg4.encoders are missing from the WSA variant of android. I was also curious if there was any way to test the theory of missing codec being the issue. If a specific codec was missing then I could go to WSA and Request them to be added to fix the issue with Exoplayer. Unless there is a way to package one of these encoders with exoplayer to ensure that the video will play even if the codec is not supplied by the device. 

iOS Information: 
When we are getting a video from an iOS device the using iOS's UIImagePicker Export tool According to the Dev the presets below this is all they are sending.

From iOS
UIImagePicker
VideoExportPreset = AVAssetExportPreset640x480
VideoQuailty = .type640x480
Video is being transcoded to h264 video and aac Audio

If there is any other information that I can help gather please let me know thank you in advance.

**Comment by adfwhitestar** [comment]
Edit after further investigation I have found that the iOS device is sending in h265 not h264

**Comment by christosts** [comment]
Apologies for the late response, I assume the issue can be closed.
