### ISSUE TITLE
Migrating to exoplayer2: error: resource string/exo_controls_shuffle_description

### ISSUE THREAD

**Issue by amandamang** [google/ExoPlayer#9997]
I'm working on updating my Android app to use exoplayer2, updated all implementations to 2.16.1, including implementation "com.google.android.exoplayer:exoplayer-ui:2.16.1". Can't build because "Android resource linking failed error: resource string/exo_controls_shuffle_description not found."

**Comment by christosts** [comment]
There are now two strings, named `exo_controls_shuffle_on_description` and `exo_controls_shuffle_off_description` ([link to code](https://github.com/google/ExoPlayer/blob/r2.16.1/library/ui/src/main/res/values-en-rGB/strings.xml#L43-L44)). I see this change happened in release 2.11. I guess your app is referencing the old string directly and you need to update your code to reference the new string names.

I'm closing this issue but feel free to re-open if the error remains.
